// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallbacks adicionados para evitar crash (Uncaught Error: supabaseUrl is required)
// quando rodando via Docker sem as variáveis, ou quando a API proprietária estiver ativa
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://dummy-for-migration.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'dummy-key';
export const API_PROVIDER = import.meta.env.VITE_API_PROVIDER || 'supabase'; // 'supabase' | 'nestjs'

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});